apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demoapp-1"
  description: "demoapp-1"
  annotations:
    backstage.io/kubernetes-id: demoapp-1
    backstage.io/kubernetes-namespace: demoapp-1-dev
    argocd/app-name: demoapp-1-dev
    github.com/project-slug: idp-myocp/demoapp-1
    backstage.io/techdocs-ref: url:https://github.com/idp-myocp/demoapp-1
    jira/project-key: ISSUEBD
    sonarqube.org/project-key: demoapp-1
    nexus-repository-manager/docker.image-name: demoapp-1

  tags:
    - java
    - quarkus
    - ghactions
    - argocd
    - artifactory

  links:
    - url: https://devspaces.apps.home.myocp.net/#https://github.com/idp-myocp/demoapp-1?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.home.myocp.net/#https://github.com/idp-myocp/demoapp-1?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  system: system:default/janus-idp
  lifecycle: production
  owner: "group:default/janus-authors"
  providesApis:
    - "demoapp-1"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "demoapp-1"
  description: "demoapp-1"
spec:
  type: openapi
  lifecycle: production
  owner: "group:default/janus-authors"
  definition:
    $text: ./openapi.yaml