site_name: demoapp-1
site_description: User description for demoapp-1
repo_url: https://github.com/idp-myocp/demoapp-1
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - Onboard a developer to OpenShift: onboard-openshift.md
